spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
jwt:
  secretKey: secretKey
  expirationTime: 86400000
management:
  endpoints:
    web:
      exposure:
        include: '*'